# AUTOGENERATED! DO NOT EDIT! File to edit: ..\00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'saludo_a']

# %% ..\00_core.ipynb 3
def foo(var_boo):
    "Esta función no hace nada"
    if var_boo:
        print("Es verdadera")
    else:
        print("Es falsa")
        return

# %% ..\00_core.ipynb 4
def saludo_a(to):
    "Esta función saluda"
    print("olii", to)
